services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.Backend
    container_name: equip-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
   
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: equip-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app 
  
    restart: always
